# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: title (if blank, full name will be used instead)


# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM

remove_HTML_comments: false

remote_theme: ppoole/hyde@v2.1.0
plugins:
- jekyll-remote-theme 
