title: ""

markdown: kramdown
kramdown:
  parse_block_html: true


theme: jekyll-theme-minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jemoji
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll-assets
  - jekyll-redirect-from