# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: ""


# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  parse_block_html: true
  input: GFM
  remove_block_html_tags: true

remove_HTML_comments: false

remote_theme: poole/hyde@v2.1.0
plugins:
- jekyll-remote-theme 
