# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: sdfsdf
description: ddddd

markdown: kramdown
highlighter: rouge
kramdown:
  remove_block_html_tags: true

remote_theme: jekyll-theme-minima
